### ISSUE TITLE
.Net Core Support

### ISSUE THREAD

**Issue by lommez** [AIBrain/Librainian#5]
Hi AlBrain,

Do you have plans to release a .net core version of your library?

Thanks

**Comment by Protiguous** [comment]
I have not researched what .NET Core can offer this library.

Feel free to experiment with a fork.

**Comment by AIBrain** [comment]
I've been playing around with the changed features in .NET 5.0.
Hopefully, I can push an update soon. Maybe with the November release of .NET 5?

**Comment by Protiguous** [comment]
Everything needs unit tests.
